name: pinyinpal
description: "Pinyin database experimentation"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  mysql1: ^0.20.0
  auto_size_text: 3.0.0
  confetti: ^0.7.0
  fl_chart: ^0.66.0
  neon: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  fonts:
  - family: LibreFranklin
    fonts:
    - asset: assets/fonts/LibreFranklin-SemiBold.ttf
    - asset: assets/fonts/LibreFranklin-Bold.ttf
  uses-material-design: true
  assets:
    - assets/images/