name: pinyinpal
description: "Pinyin database experimentation"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  camera: ^0.10.0+4
  flutter:
    sdk: flutter
  mysql1: ^0.20.0
  auto_size_text: 3.0.0
  confetti: ^0.7.0
  fl_chart: ^0.66.0
  neon: ^0.1.0
  newton_particles: ^0.1.7
  flutter_dotenv: ^5.1.0
  http: ^1.2.0
  line_awesome_flutter: ^2.0.0
  provider: ^5.0.0
  flutter_inset_box_shadow: ^1.0.8
  flutter_svg: ^1.0.0
  iconify_flutter: ^0.0.5
  google_nav_bar: ^5.0.6
  vertical_card_pager: ^1.5.0
  just_audio: ^0.9.36
  google_mlkit_text_recognition: ^0.4.0
  permission_handler: ^10.2.0
  path_provider: ^2.1.2
  flutter_secure_storage: ^9.0.0
  preload_page_view: ^0.2.0
  video_player: ^2.8.2
  translator: ^1.0.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  fonts:
  - family: LibreFranklin
    fonts:
    - asset: assets/fonts/LibreFranklin-SemiBold.ttf
    - asset: assets/fonts/LibreFranklin-Bold.ttf
  uses-material-design: true
  assets:
    - assets/images/
    - assets/json/
    - .env